apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
    containers:
    - image: nginx
      name: webserver
      volumeMounts:
      - mountPath: /giropops
        name: primeiro-emptydir
      resources:
        limits:
          cpu: "1"
          memory: "128Mi"
        requests:
          cpu: "0.5"
          memory: "64Mi"
    - image: ubuntu
      name: ubuntu
      volumeMounts:
      - mountPath: /giropops
        name: primeiro-emptydir
      args:
      - sleep
      - "1800"
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          cpu: "0.3"
          memory: "64Mi"
    volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: "256Mi"
    dnsPolicy: ClusterFirst
    restartPolicy: Always