apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
    - image: nginx
      name: nginx-giropops
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 5000Mi
          cpu: "0.5"
        requests:
          memory: 4400Mi
          cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
