apiVersion: v1
kind: Pod
metadata:
  name: nginx-https
  labels:  
    app: nginx
spec:
  containers:
    - name: nginx-https
      image: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-tls
          mountPath: /etc/nginx/tls
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: nginx-secret
      items:
        - key: tls.crt
          path: nginx.crt
        - key: tls.key
          path: nginx.key